### ISSUE TITLE
Items are cleared/wiped and reset upon login to the creative server.

### ISSUE THREAD

**Issue by Cpeers1** [Cpeers1/Centuria#38]
We need to store variables for the player on the server about whether they have been given their creative items or not.
Right now, it always resets the item list upon login, making harvesting completely pointless.

**Comment by SkySwimmer** [comment]
Actually creative mode shouldn't need harvesting, thats for the standard server, the bug i thought you meant is fixed, but the mechanic giving giving every resource remains
